site_name: Middleware Tutorial

theme:
  name: 'material'
  feature:
    tabs: true
  font:
    text: 'Work Sans'
    code: 'Roboto Mono'
  palette:
    primary: 'white'
    accent: 'indigo'
  favicon: 'https://forum.holochain.org/uploads/default/original/1X/79f6577e3c8102e1f0caf8d2f43d4fcf472a3e34.png'

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.betterem
